/*
 * Copyright 2019 pc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.metamug.exec;

import com.metamug.entity.Response;

/**
 *
 * @author pc
 */
public interface ResponseFormatter {

    /**
     * Format final response generated by server
     *
     * @param response
     * @return
     */
    public String format(Response response);
}
